FROM amazoncorretto:17
ENV ARTIFACT_NAME=cafe-backend-0.0.1-SNAPSHOT.jar
ENV APP_HOME=/usr/app/

COPY cafe-backend-0.0.1-SNAPSHOT.jar ${APP_HOME}
WORKDIR $APP_HOME
EXPOSE 8080

ENTRYPOINT exec java -jar ${ARTIFACT_NAME}